// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_one_for_the_piggy_bank = "CgkIz8uioKkVEAIQAg"; // <GPGSID>
        public const string achievement_flight_of_the_icarus = "CgkIz8uioKkVEAIQCA"; // <GPGSID>
        public const string achievement_incremental = "CgkIz8uioKkVEAIQDQ"; // <GPGSID>
        public const string achievement_saving_for_retirement = "CgkIz8uioKkVEAIQBQ"; // <GPGSID>
        public const string achievement_hidden_unlock_ach = "CgkIz8uioKkVEAIQDg"; // <GPGSID>
        public const string achievement_coin_collector = "CgkIz8uioKkVEAIQAw"; // <GPGSID>
        public const string achievement_get_rekt = "CgkIz8uioKkVEAIQCw"; // <GPGSID>
        public const string achievement_to_the_moon = "CgkIz8uioKkVEAIQCQ"; // <GPGSID>
        public const string achievement_the_bank = "CgkIz8uioKkVEAIQBg"; // <GPGSID>
        public const string leaderboard_the_best_distances = "CgkIz8uioKkVEAIQAQ"; // <GPGSID>
        public const string achievement_unlock_achievement = "CgkIz8uioKkVEAIQDA"; // <GPGSID>
        public const string achievement_hidden_incremental = "CgkIz8uioKkVEAIQDw"; // <GPGSID>
        public const string achievement_aces_high = "CgkIz8uioKkVEAIQBw"; // <GPGSID>
        public const string achievement_learning_to_fly = "CgkIz8uioKkVEAIQBA"; // <GPGSID>
        public const string achievement_kamikaze = "CgkIz8uioKkVEAIQCg"; // <GPGSID>

}

